{% include 'Makefile-base.j2' %}

{% set phony = ['help'] %}
{% do phony.append('format-md') %}
{% if has_docs %}{% do phony.extend(['doc', 'check-access']) %}{% endif %}
{% do phony.extend(['clean', 'clean-pkg']) %}
.PHONY: {{ phony | join(' ') }}

{% include 'Makefile-doc.j2' %}
{% include 'Makefile-pkg.j2' %}

clean: clean-pkg
